name: Java CI with Gradle
#event like when this happens the workflow works
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]




# this the the part the works when the event happens  
jobs:
  build:

    runs-on: ${{matrix.os}}
# we want to add more Os's not only ubuntu so do this
    strategy: 
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' 
    - name: grant permissions for Gradle
      run: chmod +x gradlew 

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
  #publish:  #this is another job to publish it
    #needs: build  # we are saying that to publish BUILD job is required







